

# Code to compute "damage function" - i.e. projected global damages by 2100 at different values of mean temperature increase relative to pre-industrial.  
#   These values range from 0.8C above preindustrial (current warming above preindustrial) to 6C above preindustrial (=5.2C above current)

# To match to IAM data without have to interpolated between projected values, we evaluate over the mean temperatures that were evaluated by at least one of the three main IAMs reported in the Revesz et al 2014 data. 
#   This is computed for different regression models, and different underlying socioeconomic scenarios.

#   We do this for regression point estimates for all regression models and socioeconomics scenarios, and then for SSP5 and pooled model calculate for all bootstrapped regression runs to quantify full uncertainty (for figure 5d)

rm(list = ls())

require(maptools)
require(fields)
require(classInt)
require(plotrix)
require(data.table)
require(dplyr)
require(ncdf)
require(raster)
library(maps)
library(wq)
library(ggplot2)
library(xtable)
library(reshape2)
"%&%"<-function(x,y)paste(x,y,sep="")  #define a function for easy string pasting


# Read in scenario data generated in ComputeMainProjections.R script
load(file="data/output/projectionOutput/popProjections.Rdata")
load(file="data/output/projectionOutput/growthProjections.Rdata")

# Read in projections of future temperature change, generated by the getTemperatureChange.R script
#   These are population-weighted country level projections averaged across all CMIP5 models
Tchg <- read.csv("data/input/CCprojections/CountryTempChange_RCP85.csv")
Tchg <- merge(popProjections[[1]][,1:3],Tchg,by.x="iso",by.y="GMI_CNTRY")
Tchg <- Tchg[Tchg$CNTRY_NAME%in%c("West Bank","Gaza Strip","Bouvet Island")==F,]  #these have the same iso code as israel and norway, respectively, which messes up the merge
Tconv <- Tchg$Tconv  #these are the "conversion factors":  i.e. what you multiply the global mean temp by to get the country-level change in temp.  again, this is based on RCP8.5 ensemble mean 

scens <- c("base","SSP"%&%1:5)  #vector defining the scenarios
sn = c(1,4,6)  #scenarios in the scens vector we are going to evaluate
yrs <- 2010:2099


# NOW COMPUTE DAMAGE FUNCTION ESTIMATES FOR FOUR MAIN HISTORICAL MODELS AND EACH SOCIOECONOMIC SCENARIO
#   Doing this for different amounts of assumed warming by 2100, as explained in text and SOM

iam <- read.csv("data/input/IAMdata/ProcessedKoppData.csv")
mods <- c("DICE","FUND","PAGE")
iam <- iam[iam$IAM%in%mods,]
inc <- sort(unique(iam$T[iam$T<=6 & iam$T>1]))  #temperatures under which some IAM was run
incs <- c(0.8,inc)  #adding in a zero increase relative to today (=0.8 increase relative to preindustrial)

####################################################################################################
# POOLED MODEL WITH NO LAGS
####################################################################################################

prj <- read.csv("data/output/bootstrap/bootstrap_noLag.csv")  #bootstrapped projections, all obs
np = dim(prj)[1]  #number of bootstrap replicates we ran. the first one is the one from the baseline model

tots = array(dim=c(length(incs),length(sn),2))  #array to hold total global GDP with and without climate change in 2099, for each scenario and temperature increase
dimnames(tots) <- list(incs,scens[sn],c("avgGDPcapCC","avgGDPcapNoCC"))

for (dt in 1:length(incs)) {  
  dtm <- (incs[dt] - 0.8)*Tconv  #calculate the country-specific temperature rise for the particular global mean increase, RELATIVE TO PRE-INDUSTRIAL so we can match IAMs.  
  # We assume an increase from pre-industrial to present day of 0.8C, so a 1C global increase to 2100 relative to pre-industrial means that we still have 1 - 0.8 = 0.2C left to go over the 21st century
  # we then convert this to country-specific estimates of warming, using our conversion factors from RCP8.5
  ccd <- dtm/length(yrs)  #rate of increase in temperature per year.
  
  # now loop over SSP scenarios and our own scenario. 
  for (scen in sn) {
    
    growthproj <- growthProjections[[scen]]
    popproj <- popProjections[[scen]]
    
    basegdp = popproj$gdpCap  #baseline GDP/cap
    temp <- popproj$meantemp #baseline temperature
    
    GDPcapCC = GDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs)))  #array to fill with GDP/cap for each country
    dimnames(GDPcapCC) <- dimnames(GDPcapNoCC) <- list(growthproj[,1],yrs)
    GDPcapCC[,1] = GDPcapNoCC[,1] = basegdp  #initialize with baseline per cap GDP

      tt=1    # evaluating our regression point estimate 
      bg = prj$temp[tt]*temp + prj$temp2[tt]*temp*temp  #this finds the predicted growth level for each country's temperature for the particular bootstrap run
      for (i in 2:length(yrs)) {
        j = i - 1
        y = yrs[i]
        basegrowth <- growthproj[,which(names(growthproj)==y)]
        GDPcapNoCC[,i] = GDPcapNoCC[,j]*(1+basegrowth)  #last year's per cap GDP times this years growth rate, as projected by scenario
        newtemp = temp+j*ccd
        dg = prj$temp[tt]*newtemp + prj$temp2[tt]*newtemp*newtemp  #predicted growth under new temperature
        dg[newtemp>30] = prj$temp[tt]*30 + prj$temp2[tt]*30*30  #constrain response to response at 30C if temp goes above that.  this is so we are not projecting out of sample
        
        diff = dg - bg  #difference between predicted baseline growth and predicted growth under new temp
        GDPcapCC[,i] = GDPcapCC[,j]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate-adjusted growth rate for this year
      }
      wt = popproj[,which(names(popproj)==y)]  #population weights 
      tots[dt,which(sn==scen),1] <- round(weighted.mean(GDPcapCC[,90],wt),0)
      tots[dt,which(sn==scen),2] <- round(weighted.mean(GDPcapNoCC[,90],wt),0)
      GDPcapCC <- GDPcapNoCC <- NULL
  }  #end scenario loop
  }  # end temperature increase loop
  
save(tots,file="data/output/projectionOutput/DamageFunction_pooled.Rdata")
  


####################################################################################################
# RICH/POOR MODEL WITH NO LAGS
####################################################################################################

#   We have different response functions for countries that were above or below median income in the historical sample.  Countries move onto
#     the rich-country response function in the future if their income rises above the historical median income (and vice versa if it falls).
#     Depending where they are in the temperature distribution when this happens, the marginal effect of temperature on growth could change sign

prj <- read.csv("data/output/bootstrap/bootstrap_richpoor.csv")  #interacted model, all obs

tots = array(dim=c(length(incs),length(sn),2))  #array to hold total global GDP with and without climate change in 2099, for each scenario and temperature increase
dimnames(tots) <- list(incs,scens[sn],c("avgGDPcapCC","avgGDPcapNoCC"))

for (dt in 1:length(incs)) {  
  dtm <- (incs[dt] - 0.8)*Tconv   
  ccd <- dtm/length(yrs)  #rate of increase in temperature per year.
  
  for (scen in sn) {
    
    growthproj <- growthProjections[[scen]]
    popproj <- popProjections[[scen]]
    
    basegdp = popproj$gdpCap  #baseline GDP/cap
    medgdp <- median(basegdp)
    temp <- popproj$meantemp  #baseline temperature.  
    
    GDPcapCC = GDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs)))  #array to fill with GDP/cap for each country
    GDPcapCC[,1] = GDPcapNoCC[,1] = basegdp  #initialize with baseline per cap GDP

  tt=1
  for (i in 2:length(yrs)) {
        j = i - 1
        y <- yrs[i]
        #baseline growth rate from SSP
        basegrowth <- growthproj[,which(names(growthproj)==y)]
        
        #was country poor last year in climate change world?
        poor <- GDPcapCC[,j]<=medgdp
        
        #calculate appropriate predicted growth rates in world without climate change
        bg = prj$temp[tt]*temp + prj$temp2[tt]*temp*temp  #predicted growth level for rich countries absent climate change
        bg[poor] = prj$temppoor[tt]*temp[poor] + prj$temp2poor[tt]*temp[poor]*temp[poor]  #predicted growth level for poor countries absent climate change
        
        GDPcapNoCC[,i] = GDPcapNoCC[,j]*(1+basegrowth)  #last year's per cap GDP times this years growth rate
        newtemp = temp+j*ccd
        dg = prj$temp[tt]*newtemp + prj$temp2[tt]*newtemp*newtemp  #predicted growth under new temperature for rich countries
        dg[poor] = prj$temppoor[tt]*newtemp[poor] + prj$temp2poor[tt]*newtemp[poor]*newtemp[poor]  #predicted growth for poor countries
        
        dg[newtemp>30 & poor==0] = prj$temp[tt]*30 + prj$temp2[tt]*30*30  #constrain response to response at 30C if temp goes above that for rich countries.  this is so we are not projecting out of sample
        dg[newtemp>30 & poor==1] = prj$temppoor[tt]*30 + prj$temp2poor[tt]*30*30  #constrain response to response at 30C for poor countries  
        diff = dg - bg  #difference between predicted baseline growth and predicted growth under new temp
        GDPcapCC[,i] = GDPcapCC[,j]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate adjusted growth rate for this year
      }
      wt = popproj[,which(names(popproj)==y)]  #population weights 
      tots[dt,which(sn==scen),1] <- round(weighted.mean(GDPcapCC[,90],wt),0)
      tots[dt,which(sn==scen),2] <- round(weighted.mean(GDPcapNoCC[,90],wt),0)
      GDPcapCC <- GDPcapNoCC <- NULL
    }  #end scenario loop
  }  # end temperature increase loop
  
save(tots,file="data/output/projectionOutput/DamageFunction_richpoor.Rdata")



####################################################################################################
# POOLED MODEL WITH 5 LAGS
####################################################################################################

prj <- read.csv("data/output/bootstrap/bootstrap_5lag.csv")  #bootstrapped projections of model with 5 lags

tots = array(dim=c(length(incs),length(sn),2))  #array to hold total global GDP with and without climate change in 2099, for each scenario and temperature increase
dimnames(tots) <- list(incs,scens[sn],c("avgGDPcapCC","avgGDPcapNoCC"))

for (dt in 1:length(incs)) {  
  dtm <- (incs[dt] - 0.8)*Tconv   
  ccd <- dtm/length(yrs)  #rate of increase in temperature per year.
  
  for (scen in sn) {
    
    growthproj <- growthProjections[[scen]]
    popproj <- popProjections[[scen]]
    
    basegdp = popproj$gdpCap  #baseline GDP/cap
    temp <- popproj$meantemp  #baseline temperature.  
    
    GDPcapCC = GDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs)))  #array to fill with GDP/cap for each country
    GDPcapCC[,1] = GDPcapNoCC[,1] = basegdp  #initialize with baseline per cap GDP

    tt=1 
      bg = prj$tlin[tt]*temp + prj$tsq[tt]*temp*temp  #this finds the predicted growth level for each country's temperature for the particular bootstrap run
      for (i in 2:length(yrs)) {
        j = i - 1
        y = yrs[i]
        basegrowth <- growthproj[,which(names(growthproj)==y)]
        GDPcapNoCC[,i] = GDPcapNoCC[,j]*(1+basegrowth)  #last year's per cap GDP times this years growth rate, as projected by scenario
        newtemp = temp+j*ccd
        dg = prj$tlin[tt]*newtemp + prj$tsq[tt]*newtemp*newtemp  #predicted growth under new temperature
        dg[newtemp>30] = prj$tlin[tt]*30 + prj$tsq[tt]*30*30  #constrain response to response at 30C if temp goes above that.  this is so we are not projecting out of sample
        
        diff = dg - bg  #difference between predicted baseline growth and predicted growth under new temp
        GDPcapCC[,i] = GDPcapCC[,j]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate-adjusted growth rate for this year
      }
      wt = popproj[,which(names(popproj)==y)]  #population weights 
      tots[dt,which(sn==scen),1] <- round(weighted.mean(GDPcapCC[,90],wt),0)
      tots[dt,which(sn==scen),2] <- round(weighted.mean(GDPcapNoCC[,90],wt),0)
      GDPcapCC <- GDPcapNoCC <- NULL
  }  #end scenario loop
}  # end temperature increase loop

save(tots,file="data/output/projectionOutput/DamageFunction_pooled5lag.Rdata")

####################################################################################################
# RICH/POOR MODEL WITH 5 LAGS
####################################################################################################

prj <- read.csv("data/output/bootstrap/bootstrap_richpoor_5lag.csv")  #interacted model, all obs
np = dim(prj)[1]  #number of bootstrap replicates we ran. the first one is the one from the baseline model

for (dt in 1:length(incs)) {  
  dtm <- (incs[dt] - 0.8)*Tconv   
  ccd <- dtm/length(yrs)  #rate of increase in temperature per year.
  
  for (scen in sn) {
    
    growthproj <- growthProjections[[scen]]
    popproj <- popProjections[[scen]]
    
    basegdp = popproj$gdpCap  #baseline GDP/cap
    medgdp <- median(basegdp)
    temp <- popproj$meantemp  #baseline temperature.  
    
    GDPcapCC = GDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs)))  #array to fill with GDP/cap for each country
    GDPcapCC[,1] = GDPcapNoCC[,1] = basegdp  #initialize with baseline per cap GDP

      tt=1
      for (i in 2:length(yrs)) {
        j = i - 1
        y <- yrs[i]
        #baseline growth rate from SSP
        basegrowth <- growthproj[,which(names(growthproj)==y)]
        
        #was country poor last year in climate change world?
        poor <- GDPcapCC[,j]<=medgdp
        
        #calculate appropriate predicted growth rates in world without climate change
        bg = prj$tlin[tt]*temp + prj$tsq[tt]*temp*temp  #predicted growth level for rich countries absent climate change
        bg[poor] = prj$tlinpoor[tt]*temp[poor] + prj$tsqpoor[tt]*temp[poor]*temp[poor]  #predicted growth level for poor countries absent climate change
        
        GDPcapNoCC[,i] = GDPcapNoCC[,j]*(1+basegrowth)  #last year's per cap GDP times this years growth rate
        newtemp = temp+j*ccd
        dg = prj$tlin[tt]*newtemp + prj$tsq[tt]*newtemp*newtemp  #predicted growth under new temperature for rich countries
        dg[poor] = prj$tlinpoor[tt]*newtemp[poor] + prj$tsqpoor[tt]*newtemp[poor]*newtemp[poor]  #predicted growth for poor countries
        
        dg[newtemp>30 & poor==0] = prj$tlin[tt]*30 + prj$tsq[tt]*30*30  #constrain response to response at 30C if temp goes above that for rich countries.  this is so we are not projecting out of sample
        dg[newtemp>30 & poor==1] = prj$tlinpoor[tt]*30 + prj$tsqpoor[tt]*30*30  #constrain response to response at 30C for poor countries  
        
        diff = dg - bg  #difference between predicted baseline growth and predicted growth under new temp
        GDPcapCC[,i] = GDPcapCC[,j]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate adjusted growth rate for this year
      }
      wt = popproj[,which(names(popproj)==y)]  #population weights 
      tots[dt,which(sn==scen),1] <- round(weighted.mean(GDPcapCC[,90],wt),0)
      tots[dt,which(sn==scen),2] <- round(weighted.mean(GDPcapNoCC[,90],wt),0)
      GDPcapCC <- GDPcapNoCC <- NULL
    }  #end scenario loop
  }  # end temperature increase loop
  
  save(tots,file="data/output/projectionOutput/DamageFunction_richpoor5lag.Rdata")


  
####################################################################################################
# FINALLY, CALCULATE FULL REGRESSION UNCERTAINTY FOR POOLED MODEL, SSP5.  
#     that is, evaluate across all bootstrap runs for the pooled model
####################################################################################################
  
  prj <- read.csv("data/output/bootstrap/bootstrap_noLag.csv")  #bootstrapped projections, all obs
  np = dim(prj)[1]  #number of bootstrap replicates we ran. the first one is the one from the baseline model
  scen = 6
  
  for (dt in 1:length(incs)) {  
    dtm <- (incs[dt] - 0.8)*Tconv   
    ccd <- dtm/length(yrs)  #rate of increase in temperature per year.
    

      growthproj <- growthProjections[[scen]]
      popproj <- popProjections[[scen]]
      
      basegdp = popproj$gdpCap  #baseline GDP/cap
      temp <- popproj$meantemp #baseline temperature
      
      GDPcapCC = GDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs),np))  #array to fill with GDP/cap for each country
      dimnames(GDPcapCC) <- dimnames(GDPcapNoCC) <- list(growthproj[,1],yrs,1:np)
      GDPcapCC[,1,] = GDPcapNoCC[,1,] = basegdp  #initialize with baseline per cap GDP
      tots = array(dim=c(np,length(yrs),2))  #array to hold average global per cap GDP and total global GDP across scenarios, with and without climate change
      dimnames(tots) <- list(1:np,yrs,c("avgGDPcapCC","avgGDPcapNoCC"))
      
      for (tt in 1:np) {  #looping over bootstrap estimates
        bg = prj$temp[tt]*temp + prj$temp2[tt]*temp*temp  #this finds the predicted growth level for each country's temperature for the particular bootstrap run
        for (i in 2:length(yrs)) {
          j = i - 1
          y = yrs[i]
          basegrowth <- growthproj[,which(names(growthproj)==y)]
          GDPcapNoCC[,i,tt] = GDPcapNoCC[,j,tt]*(1+basegrowth)  #last year's per cap GDP times this years growth rate, as projected by scenario
          newtemp = temp+j*ccd
          dg = prj$temp[tt]*newtemp + prj$temp2[tt]*newtemp*newtemp  #predicted growth under new temperature
          dg[newtemp>30] = prj$temp[tt]*30 + prj$temp2[tt]*30*30  #constrain response to response at 30C if temp goes above that.  this is so we are not projecting out of sample
          
          diff = dg - bg  #difference between predicted baseline growth and predicted growth under new temp
          GDPcapCC[,i,tt] = GDPcapCC[,j,tt]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate-adjusted growth rate for this year
          
          #now calculate global average per cap GDP, weighting by population
          wt = popproj[,which(names(popproj)==y)]  #population weights 
          tots[tt,i,1] <- round(weighted.mean(GDPcapCC[,i,tt],wt),0)
          tots[tt,i,2] <- round(weighted.mean(GDPcapNoCC[,i,tt],wt),0)
        }
      }
      save(tots,file="data/output/projectionOutput/DamageFunction_pooled_"%&%scens[scen]%&%"_"%&%incs[dt]%&%".Rdata")
      GDPcapCC <- GDPcapNoCC <- NULL
      print("dt = "%&%dt)
      
    }
  