
# Script to make Extended Data Figure 3


rm(list = ls())

require(maptools)
require(fields)
require(classInt)
require(plotrix)
require(data.table)
require(dplyr)
require(ncdf)
require(raster)
library(maps)
library(wq)
library(ggplot2)
library(xtable)
library(reshape2)
"%&%"<-function(x,y)paste(x,y,sep="")  #define a function for easy string pasting


# Read in scenario data generated in ComputeMainProjections.R script
load(file="data/output/projectionOutput/popProjections.Rdata")
load(file="data/output/projectionOutput/growthProjections.Rdata")
yrs <- 2010:2099

# Read in projections of future temperature change, generated by the getTemperatureChange.R script
#   These are population-weighted country level projections averaged across all CMIP5 models
Tchg <- read.csv("data/input/CCprojections/CountryTempChange_RCP85.csv")
Tchg <- merge(popProjections[[1]][,1:3],Tchg,by.x="iso",by.y="GMI_CNTRY")
Tchg <- Tchg[Tchg$CNTRY_NAME%in%c("West Bank","Gaza Strip","Bouvet Island")==F,]
Tchg <- Tchg$Tchg # just keep the vector of temperature changes, since sort order is now correct

# set temperature change for all runs
#dtm <- 4.3  #4.3C is the average land surface increase under RCP8.5
dtm <- Tchg   #the country-specific changes
scens <- c("base","SSP"%&%1:5)
ccd <- dtm/length(yrs)  #rate of increase in temperature per year.  


#initialize figure
pdf(file="figures/ExtendedDataFigs_Input/Fig3.pdf",width=8,height=8, useDingbats = F)
par(mfrow=c(2,2), mar=c(4,4,2,2))

####################################################################################################
# Make panel A
####################################################################################################

prj <- read.csv("data/output/DJO/Coefficients_DJOcompare.csv")
np1 <- dim(prj)[1]

colz = c("black","orange","red","blue","black","orange")
ltyz = c(1,1,1,1,2,2)
x = 0:30

# pdf(file="figures/ExtendedDataFigs_Input/Fig4_A.pdf",width=5,height=5)
plot(1,ylim=c(-0.15,0.05),xlim=c(0,30),type="l",las=1,ylab = "growth rate of GDP/capita",xlab="temperature")
abline(h=0,lwd=0.5)
abline(h=seq(-60,20,20),lty=2,col="grey")
for (i in 1:np1) {
  y = prj$b1[i]*x + prj$b2[i]*x*x - prj$b1[i]*20 - prj$b2[i]*20*20
  lines(x,y,lwd=2,col=colz[i],lty=ltyz[i])
}
# dev.off()


####################################################################################################
# Make panel B
####################################################################################################

prj <- read.csv("data/output/DJO/Coefficients_DJOcompare.csv")
np1 <- dim(prj)[1]

scen=6

growthproj <- growthProjections[[scen]]
popproj <- popProjections[[scen]]

basegdp = popproj$gdpCap  #baseline GDP/cap
temp <- popproj$meantemp  #baseline temperature.  

GDPcapCC = GDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs),np1))  #array to fill with GDP/cap for each country
GDPcapCC[,1,] = GDPcapNoCC[,1,] = basegdp  #initialize with baseline per cap GDP
chgs1 = array(dim=c(np1,length(yrs)))  #array to hold global changes in GDP

for (tt in 1:np1) {
  bg = prj$b1[tt]*temp + prj$b2[tt]*temp*temp  
  for (i in 2:length(yrs)) {
    j = i - 1
    y = yrs[i]
    basegrowth <- growthproj[,which(names(growthproj)==y)]
    GDPcapNoCC[,i,tt] = GDPcapNoCC[,j,tt]*(1+basegrowth)  #last year's per cap GDP times this years growth rate, as projected by scenario
    newtemp = temp+j*ccd
    dg = prj$b1[tt]*newtemp + prj$b2[tt]*newtemp*newtemp  #predicted growth under new temperature
    dg[newtemp>30] = prj$b1[tt]*30 + prj$b2[tt]*30*30  #constrain response to response at 30C if temp goes above that.  this is so we are not projecting out of sample
    
    diff = dg - bg  #difference between predicted baseline growth and predicted growth under new temp
    GDPcapCC[,i,tt] = GDPcapCC[,j,tt]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate-adjusted growth rate for this year
    
    #now calculate global average per cap GDP, weighting by population
    wt = popproj[,which(names(popproj)==y)]  #population weights 
    chgs1[tt,i] <- weighted.mean(GDPcapCC[,i,tt],wt)/weighted.mean(GDPcapNoCC[,i,tt],wt) - 1
  }
}


# Make plot

# pdf(file="figures/ExtendedDataFigs_Input/Fig4_B.pdf",width=5,height=5)

plot(1,ylim=c(-75,45),xlim=c(2010,2100),type="l",las=1,ylab = "change in global GDP/cap (%)",xlab="year")
colz = c("black","orange","red","blue","black","orange")
ltyz = c(1,1,1,1,2,2)
abline(h=0,lwd=0.5)
abline(h=seq(-60,20,20),lty=2,col="grey")
for (i in 1:np1) {
  lines(yrs,chgs1[i,]*100,lwd=2,col=colz[i],lty=ltyz[i])
}

# dev.off()





#########################################################################
#  MAKE PANELS C AND D
#########################################################################

# First calculate impact projections for original linear model in DJO, for 0, 5, 10 lag models

#coefficents from DJO model
betaP = c(-1.347,-1.041,-0.858)/100  #temperature coefficients for poor countries: zero lag, 5 lag, 10 lag models (Table 4 in DJO 2012)
betaR = c(0.262,-0.191,-0.189)/100  # equivalent for rich countries

np2 = length(betaP)
scen=4

growthproj <- growthProjections[[scen]]
popproj <- popProjections[[scen]]

basegdp = popproj$gdpCap  #baseline GDP/cap
medgdp <- median(basegdp)
temp <- popproj$meantemp  #baseline temperature.  

djo = array(dim=c(np2,length(yrs)))  #array to hold global changes in GDP for DJO
djoGDPcapCC = djoGDPcapNoCC = array(dim=c(dim(growthproj)[1],length(yrs),np2))  #array to fill with GDP/cap for each country.  dim 3 is the different lags instead of different bootstraps
djoGDPcapCC[,1,] = djoGDPcapNoCC[,1,] = basegdp  #initialize with baseline per cap GDP

for (tt in 1:np2) {  #looping over 
  
  for (i in 2:length(yrs)) {
    j = i - 1
    y = yrs[i]
    basegrowth <- growthproj[,which(names(growthproj)==y)]
    
    #was country poor last year in climate change world?
    poor <- djoGDPcapCC[,j,tt]<=medgdp
    newtemp = temp+j*ccd
    newtemp[newtemp>30] <- 30
    dt = newtemp - temp  # again not evaluating coefficients for temperatures above 30C
    
    djoGDPcapNoCC[,i,tt] = djoGDPcapNoCC[,j,tt]*(1+basegrowth)  #last year's per cap GDP times this years growth rate, as projected by scenario
    diff = betaR[tt]*dt   #change in growth rate under new temperature, rich countries
    diff[poor] = dt[poor]*betaP[tt]  # change in growth rate for poor countries
    
    djoGDPcapCC[,i,tt] = djoGDPcapCC[,j,tt]*(1+basegrowth + diff)  #last year's GDPcap (w/ climate change) times climate-adjusted growth rate for this year
    
    #now calculate global average per cap GDP, weighting by population
    wt = popproj[,which(names(popproj)==y)]  #population weights 
    djo[tt,i] <- weighted.mean(djoGDPcapCC[,i,tt],wt)/weighted.mean(djoGDPcapNoCC[,i,tt],wt) - 1
  }
}
djo[,1] <- 0
djo <- djo*100

# load our projections
runs <- c("pooled","pooled5lag","richpoor","richpoor5lag") #historical models
scens <- c("base","SSP"%&%1:5)  #socioeconomic scenarios
yrs <- 2010:2099
scen=6
imp <- NULL
for (j in 1:2)  {  #load global predictions from baseline regression models (pooled zero lag and pooled 5 lag)
  load("data/output/projectionOutput/GlobalChanges_"%&%runs[j]%&%"_"%&%scens[scen]%&%".Rdata")
  chgs <- tots[,,1]/tots[,,2]-1
  chgs <- chgs*100
  chgs[,1] <- 0  # first year is end of baseline, so no change
  imp <- cbind(imp,chgs[1,])
}


#combine 0 and 5 lag models into 1 dataframe, that we use below for plotting
toplot <- data.frame(t(djo[1:2,]),imp)


# COMPUTE REGIONAL PROJECTIONS
iso <- read.csv("data/input/iso/ISOcountryCodes.csv")
region <- read.csv("data/input/iso/ISOregionCodes.csv")
iso <- merge(iso,region,by="sub.region.code")
scen=6 # SSP5

popproj <- popProjections[[scen]]
nms <- as.character(iso$alpha.3)
nms[nms=="COD"] <- "ZAR"  #match to our weird codes
nms[nms=="ROU"] <- "ROM"  
sum(nms%in%popproj[,1])
mm <- match(popproj[,1],nms)
rg <- iso[mm,]
rr <- unique(rg$metaRegion)

# outputing one projection per region, based on our main model (first row of bootstrap output)
rBHM <- rDJO <- array(dim=c(length(rr),length(yrs),2))
for (m in 1:2) {  #loop over zero and 5-lag models
  j <- runs[m]
  load("data/output/projectionOutput/GDPcapCC_"%&%j%&%"_"%&%scens[scen]%&%".Rdata")  #load BHM country-level projections
  load("data/output/projectionOutput/GDPcapNoCC_"%&%j%&%"_"%&%scens[scen]%&%".Rdata")
  
  for (i in 1:length(rr)) {
    zz <- which(rg$metaRegion==rr[i])
    wt = popproj[zz,which(names(popproj)%in%yrs)]  #population weights 
    rBHM[i,,m] <- diag(t(wt)%*%GDPcapCC[zz,,1])/diag(t(wt)%*%GDPcapNoCC[zz,,1]) - 1  #quicker way to get the weighted averages for each year in the region without looping over years
    rDJO[i,,m] <- diag(t(wt)%*%djoGDPcapCC[zz,,m])/diag(t(wt)%*%djoGDPcapNoCC[zz,,m]) - 1
  }
}

rBHM <- rBHM*100
rDJO <- rDJO*100


#first, global projections for zero and 5-lag models
plot(1,ylim=c(-75,45),xlim=c(2010,2100),type="l",las=1,ylab = "change in global GDP/cap (%)",xlab="year")
colz = c("orange","orange","blue","blue")
ltyz = c(1,2,1,2)
abline(h=0,lwd=0.5)
abline(h=seq(-60,40,20),lty=2,col="grey")
for (i in 1:dim(toplot)[2]) {
  lines(yrs,toplot[,i],lwd=2,col=colz[i],lty=ltyz[i])
}

# second panel of regional projections
rrn <- c("SAsia","SSA","EU","MENA","LA","OCEA","SEAsia","NA","EAsia")
plot(rBHM[,90,1],rBHM[,90,2],las=1,pch=21,bg="blue",cex=1.5,col="black",xlim=c(-100,100),ylim=c(-100,10),xlab="Change in GDP/cap in 2100 (%) from zero lag models",ylab="Change in GDP/cap in 2100 (%) from 5 lag models")
points(rDJO[,90,1],rDJO[,90,2],pch=21,bg="orange",cex=1.5,col="black")
text(rBHM[,90,1],rBHM[,90,2],rrn,pos=4,cex=0.5,col="blue")
text(rDJO[,90,1],rDJO[,90,2],rrn,pos=4,cex=0.5,col="orange")
abline(h=0,v=0,lty=2,lwd=0.5)


dev.off()
